ALTER TABLE users ADD COLUMN IF NOT EXISTS full_name VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS country_code VARCHAR DEFAULT 'MX';
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url VARCHAR;
