export interface ChessTrophy {
  title: string;
  desc: string;
  condition: (stats: any, user: any) => boolean;
}

export const CHESS_TROPHIES: ChessTrophy[] = [
  // Básicos
  { title: 'Pensador Táctico', desc: 'Resuelve al menos 1 reto de táctica', condition: (s) => s.puzzlesSolved >= 1 },
  { title: 'Superviviente del Reto', desc: 'Mantén tu racha activa resolviendo puzzles', condition: (s) => s.puzzlesSolved > 0 },
  
  // Hitos de Puzzles Resueltos (15 trofeos)
  { title: 'Iniciado en Táctica', desc: 'Resuelve 5 problemas de táctica', condition: (s) => s.puzzlesSolved >= 5 },
  { title: 'Calculador', desc: 'Resuelve 10 problemas de táctica', condition: (s) => s.puzzlesSolved >= 10 },
  { title: 'Vista de Águila', desc: 'Resuelve 25 problemas de táctica', condition: (s) => s.puzzlesSolved >= 25 },
  { title: 'Cazador de Patrones', desc: 'Resuelve 50 problemas de táctica', condition: (s) => s.puzzlesSolved >= 50 },
  { title: 'Mente Analítica', desc: 'Resuelve 100 problemas de táctica', condition: (s) => s.puzzlesSolved >= 100 },
  { title: 'Estratega de Acero', desc: 'Resuelve 200 problemas de táctica', condition: (s) => s.puzzlesSolved >= 200 },
  { title: 'Táctico Experto', desc: 'Resuelve 300 problemas de táctica', condition: (s) => s.puzzlesSolved >= 300 },
  { title: 'Visionario del Tablero', desc: 'Resuelve 400 problemas de táctica', condition: (s) => s.puzzlesSolved >= 400 },
  { title: 'Rey de los Problemas', desc: 'Resuelve 500 problemas de táctica', condition: (s) => s.puzzlesSolved >= 500 },
  { title: 'Computadora Humana', desc: 'Resuelve 750 problemas de táctica', condition: (s) => s.puzzlesSolved >= 750 },
  { title: 'Maestro de la Táctica', desc: 'Resuelve 1000 problemas de táctica', condition: (s) => s.puzzlesSolved >= 1000 },
  { title: 'Táctico Implacable', desc: 'Resuelve 1500 problemas de táctica', condition: (s) => s.puzzlesSolved >= 1500 },
  { title: 'Genio Calculador', desc: 'Resuelve 2000 problemas de táctica', condition: (s) => s.puzzlesSolved >= 2000 },
  { title: 'Oráculo del Tablero', desc: 'Resuelve 3000 problemas de táctica', condition: (s) => s.puzzlesSolved >= 3000 },
  { title: 'Leyenda Táctica', desc: 'Resuelve 5000 problemas de táctica', condition: (s) => s.puzzlesSolved >= 5000 },

  // Hitos de ELO Táctico (25 trofeos)
  { title: 'Aspirante Táctico', desc: 'Alcanza ELO 900+ Táctico', condition: (s, u) => (u?.chess_tactical_elo ?? s.tacticalElo) >= 900 },
  { title: 'Estudiante Aplicado', desc: 'Alcanza ELO 1000+ Táctico', condition: (s, u) => (u?.chess_tactical_elo ?? s.tacticalElo) >= 1000 },
  { title: 'Táctico Prometedor', desc: 'Alcanza ELO 1100+ Táctico', condition: (s, u) => (u?.chess_tactical_elo ?? s.tacticalElo) >= 1100 },
  { title: 'Ojo Entrenado', desc: 'Alcanza ELO 1200+ Táctico', condition: (s, u) => (u?.chess_tactical_elo ?? s.tacticalElo) >= 1200 },
  { title: 'Buscador de Mates', desc: 'Alcanza ELO 1300+ Táctico', condition: (s, u) => (u?.chess_tactical_elo ?? s.tacticalElo) >= 1300 },
  { title: 'Ajedrecista Sólido', desc: 'Alcanza ELO 1400+ Táctico', condition: (s, u) => (u?.chess_tactical_elo ?? s.tacticalElo) >= 1400 },
  { title: 'Peligro en el Tablero', desc: 'Alcanza ELO 1500+ Táctico', condition: (s, u) => (u?.chess_tactical_elo ?? s.tacticalElo) >= 1500 },
  { title: 'Jugador de Club', desc: 'Alcanza ELO 1600+ Táctico', condition: (s, u) => (u?.chess_tactical_elo ?? s.tacticalElo) >= 1600 },
  { title: 'Francotirador', desc: 'Alcanza ELO 1700+ Táctico', condition: (s, u) => (u?.chess_tactical_elo ?? s.tacticalElo) >= 1700 },
  { title: 'Experto en Combinaciones', desc: 'Alcanza ELO 1800+ Táctico', condition: (s, u) => (u?.chess_tactical_elo ?? s.tacticalElo) >= 1800 },
  { title: 'Fuerza Mayor', desc: 'Alcanza ELO 1900+ Táctico', condition: (s, u) => (u?.chess_tactical_elo ?? s.tacticalElo) >= 1900 },
  { title: 'Candidato a Maestro', desc: 'Alcanza ELO 2000+ Táctico', condition: (s, u) => (u?.chess_tactical_elo ?? s.tacticalElo) >= 2000 },
  { title: 'Mago de las Piezas', desc: 'Alcanza ELO 2100+ Táctico', condition: (s, u) => (u?.chess_tactical_elo ?? s.tacticalElo) >= 2100 },
  { title: 'Maestro Nacional (Táctica)', desc: 'Alcanza ELO 2200+ Táctico', condition: (s, u) => (u?.chess_tactical_elo ?? s.tacticalElo) >= 2200 },
  { title: 'Maestro FIDE (Táctica)', desc: 'Alcanza ELO 2300+ Táctico', condition: (s, u) => (u?.chess_tactical_elo ?? s.tacticalElo) >= 2300 },
  { title: 'Maestro Internacional (Táctica)', desc: 'Alcanza ELO 2400+ Táctico', condition: (s, u) => (u?.chess_tactical_elo ?? s.tacticalElo) >= 2400 },
  { title: 'Gran Maestro (Táctica)', desc: 'Alcanza ELO 2500+ Táctico', condition: (s, u) => (u?.chess_tactical_elo ?? s.tacticalElo) >= 2500 },
  { title: 'Super Gran Maestro', desc: 'Alcanza ELO 2600+ Táctico', condition: (s, u) => (u?.chess_tactical_elo ?? s.tacticalElo) >= 2600 },
  { title: 'Élite Mundial (Táctica)', desc: 'Alcanza ELO 2700+ Táctico', condition: (s, u) => (u?.chess_tactical_elo ?? s.tacticalElo) >= 2700 },
  { title: 'Candidato al Título', desc: 'Alcanza ELO 2800+ Táctico', condition: (s, u) => (u?.chess_tactical_elo ?? s.tacticalElo) >= 2800 },
  { title: 'Retador del Mundo', desc: 'Alcanza ELO 2900+ Táctico', condition: (s, u) => (u?.chess_tactical_elo ?? s.tacticalElo) >= 2900 },
  { title: 'Campeón Mundial (Táctica)', desc: 'Alcanza ELO 3000+ Táctico', condition: (s, u) => (u?.chess_tactical_elo ?? s.tacticalElo) >= 3000 },
  { title: 'Mente Cuántica', desc: 'Alcanza ELO 3100+ Táctico', condition: (s, u) => (u?.chess_tactical_elo ?? s.tacticalElo) >= 3100 },
  { title: 'Dios de la Táctica', desc: 'Alcanza ELO 3200+ Táctico', condition: (s, u) => (u?.chess_tactical_elo ?? s.tacticalElo) >= 3200 },
  { title: 'Stockfish Humano', desc: 'Alcanza ELO 3300+ Táctico', condition: (s, u) => (u?.chess_tactical_elo ?? s.tacticalElo) >= 3300 },

  // Hitos de ELO Arena (28 trofeos)
  { title: 'Gladiador de la Arena', desc: 'Juega tu primera partida en la Arena', condition: (s, u) => (u?.chess_elo ?? s.arenaElo) > 1200 },
  { title: 'Aprendiz de Arena', desc: 'Alcanza ELO 1000+ en Arena', condition: (s, u) => (u?.chess_elo ?? s.arenaElo) >= 1000 },
  { title: 'Combatiente Regular', desc: 'Alcanza ELO 1100+ en Arena', condition: (s, u) => (u?.chess_elo ?? s.arenaElo) >= 1100 },
  { title: 'Guerrero de la Arena', desc: 'Alcanza ELO 1200+ en Arena', condition: (s, u) => (u?.chess_elo ?? s.arenaElo) >= 1200 },
  { title: 'Estratega de Batalla', desc: 'Alcanza ELO 1300+ en Arena', condition: (s, u) => (u?.chess_elo ?? s.arenaElo) >= 1300 },
  { title: 'Maestro del ELO', desc: 'Alcanza ELO 1400+ en Arena o 1000+ Táctico', condition: (s, u) => (u?.chess_elo ?? s.arenaElo) >= 1400 || (u?.chess_tactical_elo ?? s.tacticalElo) >= 1000 },
  { title: 'Manager de Arena', desc: 'Alcanza ELO 1500+ en Arena', condition: (s, u) => (u?.chess_elo ?? s.arenaElo) >= 1500 },
  { title: 'Ejecutivo Fuerte', desc: 'Alcanza ELO 1600+ en Arena', condition: (s, u) => (u?.chess_elo ?? s.arenaElo) >= 1600 },
  { title: 'CEO del Tablero', desc: 'Alcanza ELO 1700+ en Arena', condition: (s, u) => (u?.chess_elo ?? s.arenaElo) >= 1700 },
  { title: 'Presidente del Club', desc: 'Alcanza ELO 1800+ en Arena', condition: (s, u) => (u?.chess_elo ?? s.arenaElo) >= 1800 },
  { title: 'Clase A', desc: 'Alcanza ELO 1900+ en Arena', condition: (s, u) => (u?.chess_elo ?? s.arenaElo) >= 1900 },
  { title: 'Experto en Arena', desc: 'Alcanza ELO 2000+ en Arena', condition: (s, u) => (u?.chess_elo ?? s.arenaElo) >= 2000 },
  { title: 'Maestro Nacional', desc: 'Alcanza ELO 2100+ en Arena', condition: (s, u) => (u?.chess_elo ?? s.arenaElo) >= 2100 },
  { title: 'Rey de la Arena', desc: 'Alcanza ELO 2200+ en Arena', condition: (s, u) => (u?.chess_elo ?? s.arenaElo) >= 2200 },
  { title: 'Maestro FIDE', desc: 'Alcanza ELO 2300+ en Arena', condition: (s, u) => (u?.chess_elo ?? s.arenaElo) >= 2300 },
  { title: 'Maestro Internacional', desc: 'Alcanza ELO 2400+ en Arena', condition: (s, u) => (u?.chess_elo ?? s.arenaElo) >= 2400 },
  { title: 'Gran Maestro', desc: 'Alcanza ELO 2500+ en Arena', condition: (s, u) => (u?.chess_elo ?? s.arenaElo) >= 2500 },
  { title: 'Emperador del Tablero', desc: 'Alcanza ELO 2600+ en Arena', condition: (s, u) => (u?.chess_elo ?? s.arenaElo) >= 2600 },
  { title: 'Súper Gran Maestro', desc: 'Alcanza ELO 2700+ en Arena', condition: (s, u) => (u?.chess_elo ?? s.arenaElo) >= 2700 },
  { title: 'Leyenda del Ajedrez', desc: 'Alcanza ELO 2800+ en Arena', condition: (s, u) => (u?.chess_elo ?? s.arenaElo) >= 2800 },
  { title: 'Campeón Mundial', desc: 'Alcanza ELO 2900+ en Arena', condition: (s, u) => (u?.chess_elo ?? s.arenaElo) >= 2900 },
  { title: 'Entidad Divina', desc: 'Alcanza ELO 3000+ en Arena', condition: (s, u) => (u?.chess_elo ?? s.arenaElo) >= 3000 },
  { title: 'AlphaZero', desc: 'Alcanza ELO 3100+ en Arena', condition: (s, u) => (u?.chess_elo ?? s.arenaElo) >= 3100 },
  { title: 'Más Allá del Límite', desc: 'Alcanza ELO 3200+ en Arena', condition: (s, u) => (u?.chess_elo ?? s.arenaElo) >= 3200 },
  { title: 'Jugador Invencible', desc: 'Alcanza ELO 3300+ en Arena', condition: (s, u) => (u?.chess_elo ?? s.arenaElo) >= 3300 },
  { title: 'Magnus Carlsen', desc: 'Alcanza ELO 3400+ en Arena', condition: (s, u) => (u?.chess_elo ?? s.arenaElo) >= 3400 },
  { title: 'Computadora Cuántica', desc: 'Alcanza ELO 3500+ en Arena', condition: (s, u) => (u?.chess_elo ?? s.arenaElo) >= 3500 },
  { title: 'Ajedrez Resuelto', desc: 'Alcanza ELO 3600+ en Arena', condition: (s, u) => (u?.chess_elo ?? s.arenaElo) >= 3600 },

  // Conceptos y Maestría Específica (30 trofeos condicionados por progresión general)
  { title: 'Dominio de la Apertura', desc: 'Demuestra control en la fase inicial del juego', condition: (s) => s.puzzlesSolved >= 20 },
  { title: 'Estratega del Medio Juego', desc: 'Domina las transiciones y planes complejos', condition: (s) => s.puzzlesSolved >= 40 },
  { title: 'Verdugo del Final', desc: 'Convierte ventajas en victorias seguras', condition: (s) => s.puzzlesSolved >= 60 },
  { title: 'Rey del Mate', desc: 'Ejecuta mates rápidos y precisos', condition: (s) => s.puzzlesSolved >= 80 },
  { title: 'Defensor de Hierro', desc: 'Salva posiciones inferiores', condition: (s) => s.puzzlesSolved >= 120 },
  { title: 'Atacante Feroz', desc: 'Lanza ofensivas imparables', condition: (s) => s.puzzlesSolved >= 140 },
  { title: 'Calculador Profundo', desc: 'Resuelve puzzles de múltiples jugadas', condition: (s) => s.puzzlesSolved >= 160 },
  { title: 'Dueño del Centro', desc: 'Comprende la importancia de las casillas centrales', condition: (s) => s.puzzlesSolved >= 180 },
  { title: 'Desarrollo Rápido', desc: 'Optimiza la salida de tus piezas', condition: (s) => s.puzzlesSolved >= 220 },
  { title: 'Seguridad del Rey', desc: 'Mantiene al rey a salvo bajo presión', condition: (s) => s.puzzlesSolved >= 240 },
  { title: 'Estructura de Peones', desc: 'Maneja las cadenas de peones con maestría', condition: (s) => s.puzzlesSolved >= 260 },
  { title: 'Alfil Bueno', desc: 'Aprovecha las diagonales abiertas', condition: (s) => s.puzzlesSolved >= 280 },
  { title: 'Caballo Poderoso', desc: 'Utiliza los caballos en puestos avanzados', condition: (s) => s.puzzlesSolved >= 320 },
  { title: 'Torres en 7ma', desc: 'Infiltra tus torres en la posición enemiga', condition: (s) => s.puzzlesSolved >= 340 },
  { title: 'Reina Dominante', desc: 'Centraliza tu pieza más poderosa', condition: (s) => s.puzzlesSolved >= 360 },
  { title: 'Sacrificio Brillante', desc: 'Entrega material por ataque o mate', condition: (s) => s.puzzlesSolved >= 380 },
  { title: 'Clavada Mortal', desc: 'Aprovecha las piezas inmovilizadas del rival', condition: (s) => s.puzzlesSolved >= 420 },
  { title: 'Ataque Doble', desc: 'Genera amenazas múltiples', condition: (s) => s.puzzlesSolved >= 440 },
  { title: 'Ataque a la Descubierta', desc: 'Sorprende con movimientos ocultos', condition: (s) => s.puzzlesSolved >= 460 },
  { title: 'Desviación Táctica', desc: 'Aleja a los defensores clave', condition: (s) => s.puzzlesSolved >= 480 },
  { title: 'Atracción Fatal', desc: 'Fuerza al rey enemigo a una red de mate', condition: (s) => s.puzzlesSolved >= 520 },
  { title: 'Intercepción', desc: 'Corta las líneas de defensa del rival', condition: (s) => s.puzzlesSolved >= 540 },
  { title: 'Eliminación del Defensor', desc: 'Destruye a la pieza que protege el objetivo', condition: (s) => s.puzzlesSolved >= 560 },
  { title: 'Bloqueo Estratégico', desc: 'Paraliza la posición enemiga', condition: (s) => s.puzzlesSolved >= 580 },
  { title: 'Zugzwang', desc: 'Obliga al rival a empeorar su posición', condition: (s) => s.puzzlesSolved >= 620 },
  { title: 'Peón Pasado', desc: 'Crea amenazas de promoción decisivas', condition: (s) => s.puzzlesSolved >= 640 },
  { title: 'Rey Activo', desc: 'Usa al rey como pieza de ataque en el final', condition: (s) => s.puzzlesSolved >= 660 },
  { title: 'Oposición', desc: 'Domina el final de peones ganando la oposición', condition: (s) => s.puzzlesSolved >= 680 },
  { title: 'Triangulación', desc: 'Pierde un tiempo para ganar la partida', condition: (s) => s.puzzlesSolved >= 720 },
  { title: 'Fortaleza Inexpugnable', desc: 'Construye una defensa que no puede ser rota', condition: (s) => s.puzzlesSolved >= 740 }
];
